### ISSUE TITLE
Scale кнопок и настройка их положения под экран 

### ISSUE THREAD

**Issue by AslanMakeG** [ValeriSavvva/Intensiv#15]
Сделать скрипт или найти иное решение, чтобы кнопки на разных экранах занимали одно положение и имели один размер

**Comment by AslanMakeG** [comment]
Скрипт не нужен, делается через Inspector.
Лера, удачи

**Comment by ValeriSavvva** [comment]
> Скрипт не нужен, делается через Inspector. Лера, удачи

ррррррррррррррррррр

**Comment by AslanMakeG** [comment]
Я сделаю быстро, лучше строчи интерфейс
