### ISSUE TITLE
Расписать сюжет так, чтобы понятно было, что программировать

### ISSUE THREAD

**Issue by AslanMakeG** [ValeriSavvva/Intensiv#16]
### Претензии к сценарию https://github.com/ValeriSavvva/Intensiv/issues/2

**Comment by AslanMakeG** [comment]
1. Не понятно какие памятники нужны, поэтому не понятно откуда их брать или если не брать, то пожалейте дизайнеров и скажите побыстрее.
2. Не понятно какие места под памятники делать и сколько этих мест будет.
3. Не понятно как подавать информацию пользователю. Либо это будет появляться окно с описанием памятника при нажатии на объект, либо это будет какая-то отдельная газета с фотками памятников и их описанием. Времени уже нет почти под реализацию, так что ДУМОЙТЕ БЫСТРЕЕ И ПОЛЕГЧЕ!!!!!!! P.S. Надо еще подумать как пользователь будет узнавать куда ставить памятник.
4. Даже если придумать, как подать информацию о памятниках, то нужно еще придумать как подать сюжет. Кто будет говорить нам, чтобы мы площадь восстановили: бомж, высшая сущность в образе текста на экране или сотрудник музея какой-то позвонит нам. Если это будет не текст, то нужен будет спрайт этого существа, с кем мы будем общаться эти невероятные 15 секунд перед самой расстановкой объектов.
5. Не понятно, что будет в конце того, как мы закончим расстанавливать памятники. Пользователь увидит какое-то сообщение? Если да, то какое?
6. Что делать с возможностью сделать скриншот? Оставляем или убираем?
7. Одна QA высказала своё мнение, что камеры должны быть не статическими, а можно было бы крутить ими в разные стороны. Оставляем статические или скрипты писать для поворота камеры? P.S. Летающей камеры точно не будет, даже не думайте.

Подумайте как можно быстрее, потому что дизайнеры и программисты тоже любят поспать в ночь перед сдачей.

**Comment by ValeriSavvva** [comment]
Напишу то, что помню с созвона.

> 6\. Что делать с возможностью сделать скриншот? Оставляем или убираем?


Этого точно не будет, все сказали это тупая никому ненужная идея.

**Comment by ValeriSavvva** [comment]
> 7\. Одна QA высказала своё мнение, что камеры должны быть не статическими, а можно было бы крутить ими в разные стороны. Оставляем статические или скрипты писать для поворота камеры? P.S. Летающей камеры точно не будет, даже не думайте.

Насчет этого от них уже ничего не зависит. Сказали статические значит будут статические времени исправлять нет.

**Comment by ValeriSavvva** [comment]
> 1. Не понятно какие памятники нужны, поэтому не понятно откуда их брать или если не брать, то пожалейте дизайнеров и скажите побыстрее.

https://github.com/ValeriSavvva/Intensiv/issues/6

**Comment by ValeriSavvva** [comment]
> 2\. Не понятно какие места под памятники делать и сколько этих мест будет.

Надо сделать минимум и сделать те 7 мест, соответственно там где располагаются выбранные памятники

**Comment by AslanMakeG** [comment]
> Надо сделать минимум и сделать те 7 мест, соответственно там где располагаются выбранные памятники

7 мест под памятники? их же 3-4 планировалось. Я спросил именно не про панель с памятниками, а на карте места.

**Comment by AslanMakeG** [comment]
> > 1. Не понятно какие памятники нужны, поэтому не понятно откуда их брать или если не брать, то пожалейте дизайнеров и скажите побыстрее.
> 
> #6

Из всех этих памятников почти готова собака, каланча и гауптвахта. И странно, что там не дом Борщёва, а какая то другая штука

**Comment by AslanMakeG** [comment]
![maxresdefault](https://user-images.githubusercontent.com/79691625/167256813-96fb55b6-a4c6-4e49-a5e4-b755f5e797a1.jpg)
