### ISSUE TITLE
Сценарий

### ISSUE THREAD

**Issue by Myndrila** [ValeriSavvva/Intensiv#2]
**Каждый** должен написать как видит сюжет игры. Ну и если вам хватит времени можете ещё и придти к чему то общему.

**Comment by ValeriSavvva** [comment]
https://docs.google.com/document/d/1vYkO-lKIeusmCz-L_6rRhNvFI57-dDmWcd0TiqQeEyM/edit

**Comment by ValeriSavvva** [comment]
### **Что нужно доработать**

Не понятно как подавать информацию пользователю. Либо это будет появляться окно с описанием памятника при нажатии на объект, либо это будет какая-то отдельная газета с фотками памятников и их описанием. Времени уже нет почти под реализацию, так что ДУМОЙТЕ БЫСТРЕЕ И ПОЛЕГЧЕ!!!!!!! P.S. Надо еще подумать как пользователь будет узнавать куда ставить памятник.
Даже если придумать, как подать информацию о памятниках, то нужно еще придумать как подать сюжет. Кто будет говорить нам, чтобы мы площадь восстановили: бомж, высшая сущность в образе текста на экране или сотрудник музея какой-то позвонит нам. Если это будет не текст, то нужен будет спрайт этого существа, с кем мы будем общаться эти невероятные 15 секунд перед самой расстановкой объектов.
Не понятно, что будет в конце того, как мы закончим расстанавливать памятники. Пользователь увидит какое-то сообщение? Если да, то какое?

**Comment by AslanMakeG** [comment]
Написать фразы сотрудника музея и что мы будем ему отвечать на эти фразы.
Наши ответы скорее всего будут просто как текст на кнопке, поэтому их лучше короткие. Или кто-то предложит свой вариант.
