### ISSUE TITLE
Границы сцены

### ISSUE THREAD

**Issue by AslanMakeG** [ValeriSavvva/Intensiv#20]
Придумать (а лучше сразу реализовать), как будут выглядеть границы сцены, чтобы это выглядело как кусок города, а не как кусок висящий в пространстве.
Туман, встроенный в юнити, вряд ли подойдёт, потому что мы не Silent Hill же делаем ёкарный бабай, но на крайний случай можно будет что-то и с ним посмотреть.

**Comment by Nastasitze** [comment]
Решение: платформу, на которой располагаются 3D-объекты будет растянута.
