### ISSUE TITLE
3D модель "Памятник собаке Бобке"

### ISSUE THREAD

**Issue by Myndrila** [ValeriSavvva/Intensiv#3]

**Comment by HovhannisyanAr** [comment]
[bobka.zip](https://github.com/ValeriSavvva/Intensiv/files/8661408/bobka.zip)

**Comment by HovhannisyanAr** [comment]
[bobka2.zip](https://github.com/ValeriSavvva/Intensiv/files/8670422/bobka2.zip)

**Comment by HovhannisyanAr** [comment]
[bobka2.zip](https://github.com/ValeriSavvva/Intensiv/files/8670455/bobka2.zip)
