### ISSUE TITLE
АНРЕАЛ ЛЕДЖЕНТ узнать что это такое

### ISSUE THREAD

**Issue by ValeriSavvva** [ValeriSavvva/Intensiv#5]

**Comment by AslanMakeG** [comment]
Плюсы анрила:
1. Блюпринты (выглядит так, будто и маленький ребенок поймёт).

Минусы:
1. Блюпринты, потому что в них разбираться мульён лет;
2. Мало материала на ютубе по нашей теме, даже если он есть, то не отвечает на мои вопросы полностью;
3. Новый интерфейс, к которому тоже надо привыкнуть и не теряться;
4. Как мне кажется, через код удобнее контролировать процесс, чем через блюпринты.

Итог: Анрил, наверное, классно, но изучить его и разработать проект можно не успеть.

**Comment by dekemen** [comment]
Плюсы Анрила:
1. Есть конструктор
2. Интуитивность
3. Большое количество инструментов
Минусы: 
1. Изучение Blueprint
2. Лицензия?
3. Изучение c++
4. Минус для нас - нехватка времени на изучение
