### ISSUE TITLE
Сделать макет Сусанинской площади (орнамент клумб)

### ISSUE THREAD

**Issue by ValeriSavvva** [ValeriSavvva/Intensiv#8]

**Comment by Nastasitze** [comment]
Деар коллеги, i hope, you will happy to see some 3d sketches from me   ;^)

![image](https://user-images.githubusercontent.com/81413003/164940001-dc00d4c0-1a0b-42f4-b208-ccb5f29e49df.png)
It's a place for plants with flowers.

**Comment by Nastasitze** [comment]
### Промежуточный этап

> ![image](https://user-images.githubusercontent.com/81413003/165465395-4ba00cf1-8492-48bf-a2ff-22a8e346edc9.png)

> Рис. 1 Сусанинская площадь. Общий макет формы

Что ещё измениться:
1.  Добавлю мелкие детали: цветовые композиции, мусорный баки.
2. Изменю толщиму стенок клумб и их высоту.

Дополнительные материалы

> ![8gaq2NtDgl15aZfP_JGc5uUN_x9njKQLn2iZuMLcwXsiAoOkCEbgEbOlm0WKf_yQKhJi9qJl73T2613gR1uUDk6C](https://user-images.githubusercontent.com/81413003/165466095-387a8623-cf2c-43fd-9553-b798310c8dec.jpg)
> Рис. 2 Промежуточный этап работы над моделью площади

> ![1](https://user-images.githubusercontent.com/81413003/165466170-04afb24d-2c82-4f34-b7f8-fad7157a3363.jpg)

**Comment by Nastasitze** [comment]
### Финальная версия 3D модели "Сусанинская площадь"

> ![image](https://user-images.githubusercontent.com/81413003/166473310-70dbdbfa-b66f-41d9-a443-e551139579eb.png)
> ![image](https://user-images.githubusercontent.com/81413003/166473717-b81b0451-d9db-4b52-b255-8ca0befd43c0.png)

---
**Вид сверху**
> ![image](https://user-images.githubusercontent.com/81413003/166473808-e1f1cfe9-ef92-4720-bc6f-a5ab68357d40.png)

**Виды сбоку**
> ![image](https://user-images.githubusercontent.com/81413003/166474073-ecbc2c17-8ed1-44cd-befe-8a9207962dd0.png)
> ![image](https://user-images.githubusercontent.com/81413003/166474289-5cc79c9d-6921-4d0e-b63b-efbc0d328bf8.png)
---



**[Ссылка на fbx-файл](https://drive.google.com/drive/folders/1V-ydCSiYTvo-gFQvfo61yli0mDomewP8?usp=sharing)**  for @MazokGood 

Файл содержит 3D модель 
  Scale: 1   1   1
  Rotation:  0   0   0

Кроме того, там есть камера, которая правильно позиционирует модель.


---
@ValeriSavvva  @dekemen   @Myndrila   @MazokGood 
Прошу вас согласовать
